steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - app
      - deploy
      - 'FE/app.yaml'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY
